import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import requests from '../utils/requests';
import { ThumbUpIcon } from '@heroicons/react/outline';

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <Nav />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const genre = ctx.query.genre;

  const res = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url // fallback to fetchTrending when user is at the homepage
    }`
  );

  const jsonResponse = await res.json();

  return {
    props: {
      results: jsonResponse.results,
    },
  };
}
